#! /usr/bin/env bash

set -e
set -x

# location of android NDK
#NDK_PATH=$PWD/../contrib/android-ndk-r12

NDK_PATH=$ANDROID_NDK_PATH

WAFOPTS="--disable-intelipp --disable-blas --disable-atlas --disable-jack --disable-sndfile --disable-avcodec --disable-vorbis --disable-flac --disable-sndfile --disable-avcodec"

# set these variables to change the default values
[ -z $PLATFORM ] && PLATFORM=android-28
[ -z $ARCH ] && ARCH=arm64

# location nof the standalone toolchains, created with
# $NDK_PATH/build/tools/make-standalone-toolchains.sh
NDK_TOOLCHAINS=$NDK_PATH/toolchains

# location of the current toolchain
CURRENT_TOOLCHAIN=$NDK_TOOLCHAINS/toolchain-$PLATFORM-$ARCH

# if it does not exist, create the toolchain
[ -d $CURRENT_TOOLCHAIN ] || \
  $NDK_PATH/build/tools/make-standalone-toolchain.sh \
    --platform=$PLATFORM --arch=$ARCH --abis=\
    --install-dir=$CURRENT_TOOLCHAIN

# aubio install destination directory
DESTDIR=$PWD/dist-$PLATFORM-$ARCH

# wipe it out if it exists
[ -d $DESTDIR ] && rm -rf $DESTDIR

# get the link to gcc
CC=`ls $CURRENT_TOOLCHAIN/bin/aarch64-linux-android-gcc`

CFLAGS="-Os" \
  CC=$CC \
  ./waf distclean configure build install --destdir=$DESTDIR \
   --verbose \
   --with-target-platform=android $WAFOPTS
